import Config

secret_key = "q9Yh2N0Y//d0+r83EgBvyMl213dt5TcaJpctnRW+qXK/11P1RfgVevik0IyMTYkL"
# Configure your database
config :elixir_internal_certificate, ElixirInternalCertificate.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "elixir_internal_certificate_dev",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :elixir_internal_certificate, ElixirInternalCertificateWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: secret_key,
  watchers: [
    app_sass: {
      DartSass,
      :install_and_run,
      [:app, ~w(--embed-source-map --source-map-urls=absolute --watch)]
    },
    npm: [
      "run",
      "postcss.watch",
      cd: Path.expand("../assets", __DIR__)
    ],
    # Start the esbuild watcher by calling Esbuild.install_and_run(:default, args)
    esbuild: {Esbuild, :install_and_run, [:app, ~w(--sourcemap=inline --watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :elixir_internal_certificate, ElixirInternalCertificateWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/elixir_internal_certificate_web/(live|views)/.*(ex)$",
      ~r"lib/elixir_internal_certificate_web/templates/.*(eex)$"
    ]
  ]

# Config Guardian Oauth2
config :elixir_internal_certificate, ElixirInternalCertificate.Account.Guardian,
  secret_key: secret_key

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
